version: '3'
services:
  nginx-proxy:
    container_name: nginx
    image: nginx
    ports:
      - "3000:3000"
    volumes:
      - "$PWD/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - newnic
    restart: always
  backend1:
    container_name: backend1
    image: nginxdemos/hello
    networks:
      - newnic
    restart: always
  backend2:
    container_name: backend2
    image: nginxdemos/hello
    networks:
      - newnic
    restart: always
networks:
  newnic:
